version: '3.8'

services:
  dev:
    build: .
    container_name: fastify-api-service
    restart: on-failure
    env_file:
      - .env
    ports:
      - 4000:4000 # host:container
    volumes:
      - ./:/usr/logs
      - ./:/app
    depends_on:
      - database
    networks:
      - fastify-postgres-network
  database:
    build: ./db
    container_name: postgres-database
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - ./:/var/lib/postgresql/data
    networks:
      - fastify-postgres-network

networks:
  fastify-postgres-network:
    driver: bridge